# Generated by Django 6.1.1 on 2026-09-07 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. DME, EEE, ECE, CSE, CIVIL', max_length=10, unique=True)),
                ('name', models.CharField(help_text='e.g. Diploma in Mechanical Engineering', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(help_text='e.g. COMP-001', max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('hr_name', models.CharField(blank=True, max_length=100)),
                ('hr_contact', models.CharField(blank=True, max_length=15)),
                ('hr_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, help_text='e.g. Automotive, Electronics, Manufacturing', max_length=100)),
                ('job_role', models.CharField(default='Diploma Trainee', max_length=100)),
                ('qualification', models.CharField(default='Diploma', max_length=100)),
                ('min_percentage', models.FloatField(default=0.0, help_text='Minimum Semester % required')),
                ('max_arrears', models.IntegerField(default=0, help_text='Maximum allowed arrears')),
                ('salary_ctc', models.CharField(help_text='e.g. ₹2.80 LPA', max_length=50)),
                ('job_location', models.CharField(default='Chennai', max_length=100)),
                ('drive_date', models.DateField()),
                ('last_date_registration', models.DateField(blank=True, null=True)),
                ('selection_process', models.TextField(blank=True, default='1. Aptitude Test\n2. Technical Interview\n3. HR Interview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eligible_departments', models.ManyToManyField(related_name='eligible_companies', to='placement_app.department')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-drive_date'],
            },
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. HYUNDAI Campus Drive 2026', max_length=200)),
                ('drive_date', models.DateField()),
                ('salary_ctc', models.CharField(help_text='e.g. 2.80 LPA', max_length=50)),
                ('job_role', models.CharField(default='Diploma Trainee', max_length=100)),
                ('min_percentage', models.FloatField(default=0.0)),
                ('max_arrears', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='ONGOING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='placement_app.company')),
                ('eligible_departments', models.ManyToManyField(related_name='drives', to='placement_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('register_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('batch', models.CharField(default='2024-2027', help_text='e.g. 2024-2027', max_length=20)),
                ('passout_year', models.IntegerField(default=2026)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_mobile', models.CharField(blank=True, max_length=15)),
                ('parent_mobile', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20)),
                ('history_of_arrears', models.BooleanField(default=False, verbose_name='History of Arrears (Yes/No)')),
                ('no_of_arrears', models.IntegerField(default=0, verbose_name='No. of Arrears')),
                ('sem1_perc', models.FloatField(default=0.0, verbose_name='I Semester Marks %')),
                ('sem2_perc', models.FloatField(default=0.0, verbose_name='II Semester Marks %')),
                ('sem3_perc', models.FloatField(default=0.0, verbose_name='III Semester Marks %')),
                ('sem4_perc', models.FloatField(default=0.0, verbose_name='IV Semester Marks %')),
                ('sem5_perc', models.FloatField(default=0.0, verbose_name='V Semester Marks %')),
                ('sem6_perc', models.FloatField(default=0.0, verbose_name='VI Semester Marks %')),
                ('x_perc', models.FloatField(default=0.0, verbose_name='X Marks %')),
                ('xii_perc', models.FloatField(default=0.0, verbose_name='XII Marks %')),
                ('iti', models.BooleanField(default=False, verbose_name='ITI (Yes/No)')),
                ('skills', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='student_resumes/')),
                ('placement_status', models.CharField(choices=[('UNPLACED', 'Unplaced'), ('PLACED', 'Placed'), ('HIGHER_STUDIES', 'Higher Studies'), ('ENTREPRENEUR', 'Entrepreneur')], default='UNPLACED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='placement_app.department')),
            ],
            options={
                'ordering': ['register_number'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin / Placement Officer'), ('STAFF', 'Staff / Department Coordinator')], default='ADMIN', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placement_app.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_attended', models.BooleanField(default=False, verbose_name='Interview Attended (Yes/No)')),
                ('aptitude', models.CharField(choices=[('PENDING', 'Pending'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('NA', 'N/A')], default='PENDING', max_length=10)),
                ('technical', models.CharField(choices=[('PENDING', 'Pending'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('NA', 'N/A')], default='PENDING', max_length=10)),
                ('hr', models.CharField(choices=[('PENDING', 'Pending'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('NA', 'N/A')], default='PENDING', max_length=10)),
                ('final_result', models.CharField(choices=[('REGISTERED', 'Registered'), ('ATTENDED', 'Attended'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('JOINED', 'Joined'), ('OPTED_OUT', 'Opted Out')], default='REGISTERED', max_length=20)),
                ('salary', models.CharField(blank=True, help_text='e.g. 2.80 LPA', max_length=50)),
                ('job_role', models.CharField(blank=True, help_text='e.g. Trainee', max_length=100)),
                ('location', models.CharField(blank=True, help_text='e.g. Chennai', max_length=100)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_records', to='placement_app.company')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_records', to='placement_app.placementdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_records', to='placement_app.student')),
            ],
            options={
                'ordering': ['student__register_number'],
                'unique_together': {('student', 'drive')},
            },
        ),
    ]
