# Generated by Django 6.1.1 on 2026-09-07 13:34

import placement_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=placement_app.models.student_photo_upload_path),
        ),
    ]
